services:
  meme-service:
    build: meme_service/
    ports:
      - "8080:8080"
    depends_on:
      - image-service
      - db-service

  image-service:
    build: image_service/
    ports:
      - "8082:8082"
    depends_on:
      - storage-service

  db-service:
    build: db_service/
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db

  storage-service:
    build: storage_service/
    ports:
      - "8083:8083"

  postgres-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - postgres-data:/postgres_data
volumes:
  postgres-data:
